// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rslkxfixkrxnxhwrjzdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzbGt4Zml4a3J4bnhod3JqemRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNTM2MjgsImV4cCI6MjA1MzcyOTYyOH0.ANH4hwZ5KBmAztsyDA_eOWTUcCEQ63tuflpMjOd4CLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);